name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install goversioninfo
      run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo

    - name: Run go generate
      run: go generate

    - name: Build amd64
      run: go build -v -o WinCryptSSHAgent.exe -ldflags -H=windowsgui
      env:
        GOARCH: amd64

    - name: Build 386
      run: go build -v -o WinCryptSSHAgent_32bit.exe -ldflags -H=windowsgui
      env:
        GOARCH: '386'
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        path: 'WinCryptSSHAgent*.exe'
